eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka
  instance:
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.zrr.pojo
server:
  port: 9091
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 178011
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
test:
  name: zrr
